; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Codename generator:
; http://www.codenamegenerator.com/ - with Colors + Birds + None

#define MyAppName "Witness"
#define CodeName "Black Puffin"
#define MyAppVersion "0.2"
#define MyAppExeName "WitnessServer.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{AF6CE8D1-73A0-4690-AD6A-8695F0AB134F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion} ({#CodeName})
DefaultDirName={autopf}\Witness
DisableProgramGroupPage=yes

; Remove the following line to run in administrative install mode (install for all users.)
; PrivilegesRequired=lowest
; PrivilegesRequiredOverridesAllowed=dialog

OutputDir=X:\Programming\Witness\Setup
OutputBaseFilename=witness_setup
Compression=lzma2/normal
SolidCompression=yes
WizardStyle=modern

ArchitecturesAllowed=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "vc_redist.x64.exe"; DestDir: {tmp}; Flags: deleteafterinstall
Source: "X:\Programming\Witness\x64\Release\WitnessServer.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "X:\Programming\Witness\x64\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: {tmp}\vc_redist.x64.exe; Parameters: "/q /passive /Q:a /c:""msiexec /q /i vcredist.msi"""; StatusMsg: "Installing VC++ 2017 Redistributables..."
Filename: {app}\Installer.exe; StatusMsg: "Running configuration tool..."

[UninstallRun]
Filename: {app}\Installer.exe; Parameters: "/uninstall"; StatusMsg: "Running configuration tool..."

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autoprograms}\Re-run setup"; Filename: "{app}\Installer.exe"
